### ISSUE TITLE
Make ->fetch_assoc() callable on APP_DbObject::DbQuery

### ISSUE THREAD

**Issue by Lucas-C** [danielholmes/bga-workbench#3]
Hi.

In the BGA framework I often call `self::DbQuery("...")->fetch_assoc()`.

However, the **bga-workbench** implementation of this method in [APP_DbObject.inc.php](https://github.com/danielholmes/bga-workbench/blob/master/src/BGAWorkbench/Stubs/APP_DbObject.inc.php#L14) always returns the `rowCount()`.

Would you agree to remove this `->rowCount()` call in `APP_DbObject::DbQuery()` please ?

Regards

**Comment by danielholmes** [comment]
@Lucas-C Done. See https://github.com/danielholmes/bga-workbench/releases/tag/v0.0.13

**Comment by Lucas-C** [comment]
Hi.
Thank you very much for the fast fix !

Sadly, I'd like to reopen this :(

The issue is that the BGA framework clearly uses the [mysqli extension](http://php.net/manual/fr/book.mysqli.php).
In order to be fully compatible (and be able to call [fetch_assoc()](http://php.net/manual/fr/mysqli-result.fetch-assoc.php), **bga-workbench** would have to use it too and not doctrine/dbal :(

I had a quick look at bga-workbench code and the following features would need to be replicated using only mysqli:
- transactions like in [Test/TableInstance.php](https://github.com/danielholmes/bga-workbench/blob/721982499720d298d30db9b321650117a29cb736/src/BGAWorkbench/Test/TableInstance.php#L153)
- easy schema creation like in [Test/DatabaseInstance.php](https://github.com/danielholmes/bga-workbench/blob/ca2b92d89a4043510d7283d573b5449270df0fba/src/BGAWorkbench/Test/DatabaseInstance.php#L135)

What do you think ? Would you agree to drop doctrine ?

I'm OK to submit a PR to start this work.

**Comment by Lucas-C** [comment]
Some alternatives:
- find a way to retrieve the `mysqli_result` from a `Doctrine\DBAL\Connection` (the underlying driver is [pdo_mysql](https://github.com/danielholmes/bga-workbench/blob/ca2b92d89a4043510d7283d573b5449270df0fba/src/BGAWorkbench/Test/DatabaseInstance.php#L59) so it should be doable)
- use a subclasse of `Doctrine\DBAL\Connection` that implements `mysqli_result` methods like `fetch_assoc`
- just do not support `self::DbQuery("...")->fetch_assoc()`. There are other ways to query results like you do in [BattleForHill218](https://github.com/danielholmes/battle-for-hill-218/blob/master/battleforhill.game.php#L176)

**Comment by danielholmes** [comment]
I don't want to dump doctrine entirely - it gives a nice interface to use in testing. But we could use mysqli directly within the BGA stubbing code. My preferred approach is your first suggestion (work out how to get the same result out of doctrine that fetch_assoc gives).

I can look into this in a few days, but if you can't wait would happily take a PR

**Comment by Lucas-C** [comment]
PR sent !

**Comment by danielholmes** [comment]
Thanks @Lucas-C ! Merged and new version released
